[build-system]
build-backend = "hatchling.build"
requires = ["hatchling"]

[project]
authors = [
    {name = "Alban Farchi", email = "alban.farchi@ecmwf.int"},
]
dependencies = [
    "bottleneck",
    "dask",
    "h5netcdf",
    "numpy",
    "pandas",
    "rich",
    "rich-click",
    "xarray",
    "zarr",
]
name = "watch-duck"
requires-python = ">= 3.11"
version = "0.1.0"

[project.scripts]
watch-duck = "watch_duck.main:cli"

[tool.ruff]
preview = true

[tool.ruff.format]
docstring-code-format = true
quote-style = "single"

[tool.ruff.lint]
flake8-quotes.inline-quotes = "single"
pydocstyle.convention = "google"
pylint.allow-magic-value-types = ["int", "str"]
pylint.max-args = 15
pylint.max-locals = 20
pylint.max-statements = 75
select = ["ALL"]
ignore = [
    # no anotations
    "ANN",
    # no copyright on files
    "CPY001",
    # no docstrings
    "D",
]

[tool.pixi.workspace]
channels = ["conda-forge"]
platforms = ["osx-arm64"]

[tool.pixi.pypi-dependencies]
watch-duck = { path = ".", editable = true }

[tool.pixi.tasks]
lint = "ruff check"
format = "ruff format --config \"lint.ignore = ['COM812']\""
download = "bin/download"
parse = "watch-duck parse"
report = "watch-duck report"
summary = "watch-duck summary"
summary_fc = "watch-duck summary -t fc"
summary_lw = "watch-duck summary -t lw"
summary_elda = "watch-duck summary -t elda"
show = [{ task = "download" }, { task = "summary_fc" }, { task = "summary_lw" }, { task = "summary_elda" }]
iver = "watch-duck iver f2025"

[tool.pixi.dependencies]
bottleneck = ">=1.6.0,<2"
dask = ">=2026.3.0,<2027"
h5netcdf = ">=1.8.1,<2"
jupyterlab = ">=4.5.6,<5"
numpy = ">=2.4.3,<3"
pandas = ">=3.0.2,<4"
rich = ">=14.3.3,<15"
rich-click = ">=1.9.7,<2"
ruff = ">=0.15.9,<0.16"
xarray = ">=2026.2.0,<2027"
zarr = ">=3.1.5,<4"
